update dependency
Moesif/moesif-servlet pull request #113
Opened 2023-10-10 20:53 UTC by qmjava

2023-10-10 20:58 UTC, dgilling requested changes
Shouldn't we remove AppConfigManager.java all together and also rely on the Java Lib for governance, config download, etc?

2023-10-10 21:01 UTC, qmjava commented
Well, there is one thing that java lib doesn't provide, which is the config update at the configured frequency.

2023-10-10 21:06 UTC, dgilling commented
@qmjava , I don't quite follow. Does it not update and cache [here](https://github.com/Moesif/moesifapi-java/blob/a4e6ac13dac2a605663602146342d8d8f0b1206c/src/main/java/com/moesif/api/controllers/APIController.java#L35) based on ETag?

2023-10-21 01:22 UTC, praves77 approved these changes

2023-10-21 01:22 UTC, merged